### ISSUE TITLE
Username sometimes adds a space after the name

### ISSUE THREAD

**Issue by johnpyp** [robotty/dank-twitch-irc#33] opened 2020-06-25 16:32 UTC
Very, very rarely I've found that usernames sometimes have a space appended to the end, and it tends to happen on the same user multiple times. Here are the few that I've found in Destiny's chat, out of millions that have been sent in the timeframe: 
![image](https://user-images.githubusercontent.com/20625636/85760329-ba6eb080-b6df-11ea-998e-cfd45c0e7b0d.png)

**Comment by johnpyp** [comment] 2020-06-25 16:59
After talking to others about this issue, it seems that:
1) It happens in approximately 0.03% of messages from the past month
2) Messages exhibiting this issue tend to be from a small subset of specific users, it isn't just random. E.g out of 134,349 messages with a space in the username, there were only 3,816 unique usernames.
3) The issue happens with independent parsing as well, so it likely is an issue with the twitch api and not dank-twitch-irc.

Given this, it could be a good idea to add `.trim()` or something to the username parser to remove extraneous whitespace.

**Comment by RAnders00** [comment] 2020-06-27 09:04
This is a twitch thing, they send a space at the end of the `display-name` tag.

**Comment by BarryCarlyon** [comment] 2020-06-28 18:06
Copying over for visibility

It's not a bug.

Some users have had a space on their display name for ages for various reasons and can manifest as a `\s` on IRC/PubSub

Usually indicates a name change back when they were done manually.

The users display name literally has a space on the end.

**Comment by RAnders00** [comment] 2020-06-28 19:00
Couldn't this be fixed for all users and then all is well? (Remove the space for the affected users)

I think "not a bug" is not a useful attitude here. Nowhere does it say that usernames are intended to have spaces at the end, neither does it say anywhere that trimming them is advisable. This is just one more oddity that literally everybody will have to work around in their implementations.

**Comment by BarryCarlyon** [comment] 2020-06-29 02:29
It's not wrong for a space to be at the end of the _display name_

Consider also

https://api.twitch.tv/helix/users?login=riotgames

username: `riotgames`
display name: `Riot Games`

**Comment by johnpyp** [comment] 2020-06-29 02:38
This is an interesting point that I didn't know about, perhaps it should be documented/noted to use the `senderUsername` field for accurate/normalized  usernames. My implementation has always used the `displayName` field simply because it was the one prevalent in the documentation examples.

**Comment by BarryCarlyon** [comment] 2020-06-29 02:58
You would extract that from the user@host part of the IRC message, like "regular" IRC.

In your OP you are pulling the display_name IRCv3 tag.

Both are two different things.

It's likely overlooked as it's "core"/traditional IRC.

https://dev.twitch.tv/docs/irc/guide#privmsg

> :<user>!<user>@<user>.tmi.twitch.tv PRIVMSG #<channel> :This is a sample message

Since you can operate chat with no capabilities and thus tags (and the display name) are optional. If you don't declare 

> CAP REQ :twitch.tv/tags

before joining any channels, then you won't get any tags at all

https://dev.twitch.tv/docs/irc/tags

**Comment by RAnders00** [comment] 2020-06-29 11:07
Fixed via e71b53356039a24b3054be330e0a5364f5c97002.
New release will follow shortly

**Closed by RAnders00** 2020-06-29 11:07 UTC

**Comment by RAnders00** [comment] 2020-06-29 11:54
Fix is now published under version v3.2.0
