### ISSUE TITLE
Message timeouts begin counting the moment it's sent to Twitch - sometimes resulting in error

### ISSUE THREAD

**Issue by 5E7EN** [robotty/dank-twitch-irc#32] opened 2020-06-23 23:07 UTC
In a case where you queue up a bunch of messages in one channel, and while those messages are still sending, you try sending another message in a second channel, the second channel's message will only send once the first messages have all finished sending - and if that isn't before 2 seconds, the lib will throw a `Timed out after waiting for response for 2000 milliseconds` error on the second channel's message.

This seems to be due to the fact that the timeout "counter" begins immediately upon dispatch of the message, and not after waiting for the previous commands to finish.

**Comment by RAnders00** [comment] 2020-06-27 09:12
Note that this also could be fixed by scaling up connections based on outgoing load. The issue is that you can queue up an practically unlimited amount of messages to be processed by Twitch if you send faster than the IRC server processed individual messages

**Comment by RAnders00** [comment] 2020-08-31 20:12
fixed via the above commit

**Closed by RAnders00** 2020-08-31 20:12 UTC
